version: '3.5'

services:
  energiodb:
    container_name: energio-database
    image: postgis/postgis:13-3.0
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    env_file:
      - energio.env
    networks:
      - energio-network
    ports:
      - 5432:5432

  app:
    container_name: energio-api
    build: .
    env_file:
      - energio.env
    volumes:
      - .:/energio
      - /usr/local/bundle:/usr/local/bundle
    networks:
      - energio-network
    ports:
      - 3000:3000
    depends_on:
      - energiodb

volumes:
  energio-postgres-data: {}

networks:
  energio-network:
    name: energio-network